const constants = {
  SOMETHING: 'SOMETHING',
  FETCH_USER_STARTED: 'FETCH_USER_STARTED',
  FETCH_USER_COMPLETED: 'FETCH_ITEM_COMPLETED',
  FETCH_USER_ERROR: 'FETCH_USER_ERROR',
  FETCH_MOVIES_STARTED: 'FETCH_MOVIES_STARTED',
  FETCH_MOVIES_ERROR: 'FETCH_MOVIES_ERROR',
  FETCH_MOVIES_COMPLETED: 'FETCH_MOVIES_COMPLETED',
  FETCH_MOVIE_BY_ID_STARTED: 'FETCH_MOVIE_BY_ID_STARTED',
  FETCH_MOVIE_BY_ID_ERROR: 'FETCH_MOVIE_BY_ID_ERROR',
  FETCH_MOVIE_BY_ID_COMPLETED: 'FETCH_MOVIE_BY_ID_COMPLETED',
};

export default constants;
