const constants = {
  SOMETHING: 'SOMETHING',
  FETCH_USER_STARTED: 'FETCH_USER_STARTED',
  FETCH_USER_COMPLETED: 'FETCH_ITEM_COMPLETED',
  FETCH_USER_ERROR: 'FETCH_USER_ERROR',
};

export default constants;
